### ISSUE TITLE
Failing Travis CI Build In AddressBook-Level4 Repo

### ISSUE THREAD

**Issue by teclu** [CS2103AUG2017-W11-B3/main#18]
**Link:** https://travis-ci.org/nus-cs2103-AY1718S1/addressbook-level4/builds/289141922

The error shown is "_ERROR:src/main/resources/view/Light.css:147: no newline at EOF._", however our repo does not even have such a file.

I have already tried to create and delete a "fake" Light.css file in that directory, but it's still failing.

**Comment by k-l-a** [comment]
Our repo's Travis CI build is also currently failing due to : 
docs/DeveloperGuide.adoc:401: trailing whitespace.

**Comment by teclu** [comment]
Wow I didn't expect you to be awake. 😆 Thanks for fixing the trailing whitespace! Our build is passing in our repo.

However, for some reason ("Light.css"???) it is still failing the Travis CI check in the [main AddressBook4  repo](https://github.com/nus-cs2103-AY1718S1/addressbook-level4/pull/15). It started when the "Update Appveyor badge link" commit was made, but I'm sure that none of us actually made this file then.

I've checked the other PRs and no one is encountering this problem.

**Comment by k-l-a** [comment]
I tried reversing that particular commit manually (since it's just copy-pasting the link), but it seems the error still persists.

**Comment by k-l-a** [comment]
By the way, even though our build is passing, there's a warning as follows : 
 [WARN] /home/travis/build/CS2103AUG2017-W11-B3/main/src/test/java/guitests/guihandles/PersonPanelHandle.java:57:33: '{' at column 33 should have line break after. [LeftCurly]

**Comment by teclu** [comment]
"**It's fine as long as it passes on your own team repo**. Your PR is not going to be merged to our repo anyway. BTW, the said file is a file **generated by Gradle during the build process.**" - Prof. Damith

We don't have to worry too much about it I guess. Thanks for the help Kevin!

**Comment by k-l-a** [comment]
Yea, I was thinking since the file itself doesn't exist, it must have been generated by Gradle on build. Couldn't find the exact source and it was much too late though.
Anyway, glad I could help!

**Comment by k-l-a** [comment]
It appears our Travis CI build is no longer failing in the PR, did someone fix this? Or was it just 'magically' fixed
