### ISSUE TITLE
Suggestion + BUG: Improve on Find command

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W11-B3/main#53]
![image](https://user-images.githubusercontent.com/19221372/32362548-289a846e-c0a5-11e7-8ed4-c7c19752032e.png)

In your command summary in the user guide, it seems that we can find all kinds of information using Find command, but when testing it, I could only find the names, and cannot find phones, tag, etc.
Maybe you can try to modify the find command in the command summary to be more specific, or you could make your findCommand more powerful!

Yuting from W09-B1

**Comment by teclu** [comment]
The command summary is slightly outdated. The actual format can be found in the locating persons section of our user guide. The correct format should be: **find [PREFIX] KEYWORD [MORE_KEYWORDS]**. Sorry for the  confusion!

**Comment by April0616** [comment]
BUG: find t/TAG_NAME doesn't work.

I key in find t/friends, but 0 person lists!

**Comment by April0616** [comment]
oh , i see, so "find t/ friends" works, but "find t/friends" doesn't work. this bug should be fixed!

**Comment by April0616** [comment]
find p/9466    doesn't work

Name: haha
Phone: 94664352

**Comment by April0616** [comment]
oh, it is suggested that you accept partial matches

**Comment by k-l-a** [comment]
It seems the user guide for the release was quite outdated, the user guide in the current version should be up to date.

Email and phone now accepts partial matches.

While your issue with the spacing of the prefix and keyword isn't strictly a bug (it was intended to be that way), based on your feedback, I have also changed for it to allow for no spacing between the prefix and keyword (i.e. `find t/friends` now work as well).

Thank you for your feedback!
