### ISSUE TITLE
UserGuide: theme light in v1.4 doesn't work

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W11-B3/main#56]
![image](https://user-images.githubusercontent.com/19221372/32362751-abfff89c-c0a6-11e7-876e-258eae6bc78e.png)

maybe you need to update the content in your user guide

**Comment by teclu** [comment]
User guide will be updated accordingly (_I have a working theme switcher; just have not merged it yet_). Thanks for the help!
