### ISSUE TITLE
Improve on the feedback of the command

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W11-B3/main#57]
when i type 'edit 8 v/ ' to delete the avatar, I cannot see 'Successfully deleted' message
![image](https://user-images.githubusercontent.com/19221372/32363031-285decfe-c0a8-11e7-902f-9144ebbbc6b0.png)

**Comment by k-l-a** [comment]
I have changed it to show this message when setting avatar to none :

![image](https://user-images.githubusercontent.com/30980251/32375244-df63b694-c0db-11e7-873e-366c32079d81.png)
