### ISSUE TITLE
Suggestion: UI improve

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W11-B3/main#62]
I cannot adjust the size of the personcard pane and the person window pane
![image](https://user-images.githubusercontent.com/19221372/32363752-c4edd766-c0ab-11e7-9077-b7cf4f48676d.png)

**Comment by teclu** [comment]
Hi April, the divider for these 2 panes is actually the thin grey line that separates them. Try clicking and dragging it and let me know if it works.
